# Generated by Django 4.0.4 on 2022-05-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StieSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('map', models.ImageField(blank=True, null=True, upload_to='')),
                ('bk_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('designer', models.CharField(blank=True, max_length=200, null=True)),
                ('backend_technology', models.CharField(blank=True, max_length=200, null=True)),
                ('frontend_technology', models.CharField(blank=True, max_length=200, null=True)),
                ('copy_right', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
