# Generated by Django 4.0.4 on 2022-06-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stiesetting',
            name='welcomeMessage_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stiesetting',
            name='welcomeMessage_sub',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
