# Generated by Django 4.0.4 on 2022-05-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_profile_age_profile_language_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
