# Generated by Django 4.0.4 on 2022-05-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_profile_telegram_profile_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='microsoft_team',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
