# Generated by Django 4.0.4 on 2022-05-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_profile_microsoft_team_profile_skype'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
