# Generated by Django 4.0.4 on 2022-05-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_employment_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
