# Generated by Django 4.0.4 on 2022-05-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_education_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(unique_for_year=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(unique_for_year=True),
        ),
    ]
