# Generated by Django 4.0.4 on 2022-05-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_alter_education_end_date_alter_education_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employment',
            options={'ordering': ['-start_date']},
        ),
    ]
