# Generated by Django 4.0.4 on 2022-05-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_alter_employment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
