# Generated by Django 4.0.4 on 2022-05-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='description',
            field=models.TextField(default='defautl'),
            preserve_default=False,
        ),
    ]
