# Generated by Django 4.0.4 on 2022-05-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0023_reference_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
