# Generated by Django 4.0.4 on 2022-05-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0024_remove_education_description_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
