# Generated by Django 4.0.4 on 2022-06-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0025_profile_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='welcome_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='welcome_subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
