# Generated by Django 4.0.4 on 2022-06-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0026_message_welcome_message_message_welcome_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='welcome_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('welcome_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='welcome_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='welcome_subject',
        ),
    ]
